// here we will import all the env variables
import dotenv from 'dotenv';
dotenv.config();

const PORT = process.env.PORT

const GPT_API_KEY = process.env.GPT_API_KEY

const PGUSER = process.env.PGUSER
const PGHOST = process.env.PGHOST
const PGDATABASE = process.env.PGDATABASE
const PGPASSWORD = process.env.PGPASSWORD
const PGPORT = process.env.PGPORT
const DATABASEURL = process.env.DATABASEURL

const RAZORPAYKEYID = process.env.RAZORPAYKEYID
const RAZORPAYKEYSECRET = process.env.RAZORPAYKEYSECRET
const RAZORPAYWEBHOOKSECRET = process.env.RAZORPAYWEBHOOKSECRET

const FIREBASE_TYPE = process.env.FIREBASE_TYPE;
const FIREBASE_PROJECT_ID = process.env.FIREBASE_PROJECT_ID;
const FIREBASE_PRIVATE_KEY_ID = process.env.FIREBASE_PRIVATE_KEY_ID;
const FIREBASE_PRIVATE_KEY = process.env.FIREBASE_PRIVATE_KEY;
const FIREBASE_CLIENT_EMAIL = process.env.FIREBASE_CLIENT_EMAIL;
const FIREBASE_CLIENT_ID = process.env.FIREBASE_CLIENT_ID;
const FIREBASE_AUTH_URI = process.env.FIREBASE_AUTH_URI;
const FIREBASE_TOKEN_URI = process.env.FIREBASE_TOKEN_URI;
const FIREBASE_AUTH_PROVIDER_X509_CERT_URL = process.env.FIREBASE_AUTH_PROVIDER_X509_CERT_URL;
const FIREBASE_CLIENT_X509_CERT_URL = process.env.FIREBASE_CLIENT_X509_CERT_URL;
const FIREBASE_UNIVERSE_DOMAIN = process.env.FIREBASE_UNIVERSE_DOMAIN;

export {
    PORT,
    GPT_API_KEY,
    PGUSER,
    PGHOST,
    PGDATABASE,
    PGPASSWORD,
    PGPORT,
    DATABASEURL,
    RAZORPAYKEYID,
    RAZORPAYKEYSECRET,
    RAZORPAYWEBHOOKSECRET,
    FIREBASE_TYPE,
    FIREBASE_PROJECT_ID,
    FIREBASE_PRIVATE_KEY_ID,
    FIREBASE_PRIVATE_KEY,
    FIREBASE_CLIENT_EMAIL,
    FIREBASE_CLIENT_ID,
    FIREBASE_AUTH_URI,
    FIREBASE_TOKEN_URI,
    FIREBASE_AUTH_PROVIDER_X509_CERT_URL,
    FIREBASE_CLIENT_X509_CERT_URL,
    FIREBASE_UNIVERSE_DOMAIN
  };