// here we will import all the env variables
import dotenv from 'dotenv';
dotenv.config();

const PORT = `${process.env.SKILL_PORT}`;

const GPT_API_KEY = `${process.env.SKILL_GPT_API_KEY}`;

const PGUSER = `${process.env.SKILL_PGUSER}`;
const PGHOST = `${process.env.SKILL_PGHOST}`;
const PGDATABASE = `${process.env.SKILL_PGDATABASE}`;
const PGPASSWORD = `${process.env.SKILL_PGPASSWORD}`;
const PGPORT = `${process.env.SKILL_PGPORT}`;
const DATABASEURL = `${process.env.SKILL_DATABASEURL}`;

const RAZORPAYKEYID = `${process.env.SKILL_RAZORPAYKEYID}`;
const RAZORPAYKEYSECRET = `${process.env.SKILL_RAZORPAYKEYSECRET}`;
const RAZORPAYWEBHOOKSECRET = `${process.env.SKILL_RAZORPAYWEBHOOKSECRET}`;

const FIREBASE_TYPE = `${process.env.SKILL_FIREBASE_TYPE}`;
const FIREBASE_PROJECT_ID = `${process.env.SKILL_FIREBASE_PROJECT_ID}`;
const FIREBASE_PRIVATE_KEY_ID = `${process.env.SKILL_FIREBASE_PRIVATE_KEY_ID}`;
const FIREBASE_PRIVATE_KEY = `${process.env.SKILL_FIREBASE_PRIVATE_KEY}`;
const FIREBASE_CLIENT_EMAIL = `${process.env.SKILL_FIREBASE_CLIENT_EMAIL}`;
const FIREBASE_CLIENT_ID = `${process.env.SKILL_FIREBASE_CLIENT_ID}`;
const FIREBASE_AUTH_URI = `${process.env.SKILL_FIREBASE_AUTH_URI}`;
const FIREBASE_TOKEN_URI = `${process.env.SKILL_FIREBASE_TOKEN_URI}`;
const FIREBASE_AUTH_PROVIDER_X509_CERT_URL = `${process.env.SKILL_FIREBASE_AUTH_PROVIDER_X509_CERT_URL}`;
const FIREBASE_CLIENT_X509_CERT_URL = `${process.env.SKILL_FIREBASE_CLIENT_X509_CERT_URL}`;
const FIREBASE_UNIVERSE_DOMAIN = `${process.env.SKILL_FIREBASE_UNIVERSE_DOMAIN}`;

export {
    PORT,
    GPT_API_KEY,
    PGUSER,
    PGHOST,
    PGDATABASE,
    PGPASSWORD,
    PGPORT,
    DATABASEURL,
    RAZORPAYKEYID,
    RAZORPAYKEYSECRET,
    RAZORPAYWEBHOOKSECRET,
    FIREBASE_TYPE,
    FIREBASE_PROJECT_ID,
    FIREBASE_PRIVATE_KEY_ID,
    FIREBASE_PRIVATE_KEY,
    FIREBASE_CLIENT_EMAIL,
    FIREBASE_CLIENT_ID,
    FIREBASE_AUTH_URI,
    FIREBASE_TOKEN_URI,
    FIREBASE_AUTH_PROVIDER_X509_CERT_URL,
    FIREBASE_CLIENT_X509_CERT_URL,
    FIREBASE_UNIVERSE_DOMAIN
  };